# Практическая работа по теме "Линейная алгебра". Выполнил студент 1 курса ББМО-01-23 Шарапов Кирилл Андреевич

## Начало работы

In [7]:
import numpy as np
!pip install memory_profiler

## 1. Докажите, что транспонирование транспонированной матрицы - это сама матрица

In [ ]:
A = np.random.randint(1, 10, size=(3, 3))
A_transposed = A.T
A_double_transposed = A_transposed.T

are_equal = np.array_equal(A_double_transposed, A)

are_equal

True

## 2. Для двух матриц $\mathbf{A}$ и $\mathbf{B}$, покажите, что сумма и транспозиция коммутируют

In [ ]:
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

AB_transposed_sum = A.T + B.T
AB_sum_transposed = (A + B).T

compare = np.array_equal(AB_transposed_sum, AB_sum_transposed)

compare

True

## 3. Для любой квадратичной матрицы $\mathbf{A}$, сумма матриц $\mathbf{A} + \mathbf{A}^\top$ всегда ли симметрична? Можете ли вы доказать это, используя только предыдущие два упражнения?

In [ ]:
A = np.random.randint(1, 10, size=(3, 3))

S = A + A.T
S_transposed = S.T

is_symmetric = np.array_equal(S, S_transposed)

is_symmetric

True

## 4. Мы определяли тензор `X` размерности (2, 3, 4). Что возвращает функция `len(X)`? Попробуйте записать ответ используя воображение, потом проверьте свой ответ в среде программирования.

In [ ]:
X = np.random.rand(2, 3, 4)

length_of_X = len(X)

length_of_X

2

## 5. Для тензора `X` произвольной размерности, всегда ли функция `len(X)` возвращает длину тензора по оси `X`? Что такое ось?

Функция len(X) для тензора всегда возвращает размер первого измерения тензора.

In [ ]:
tensor1 = np.random.rand(4, 5)
tensor2 = np.random.rand(6, 3, 2)
tensor3 = np.random.rand(2, 3, 4, 5)
tensor4 = np.random.rand(8)
tensor5 = np.random.rand(3, 7, 2, 4, 5)

lens = [len(tensor1), len(tensor2), len(tensor3), len(tensor4), len(tensor5)]
lens

[4, 6, 2, 8, 3]

В многомерных массивах (тензорах) ось — это измерение, вдоль которого происходят операции.

## 6. Запустите следующий фрагмент кода `A / A.sum(axis=1)` и проверьте полученный результат. Можете пояснить причину?

Ошибка заключается в том, что операция деления пытается выполниться без соответствующего изменения формы массива суммы для совместимости с размерами матрицы A. Правильный подход требует, чтобы результат суммирования по оси 1 (который является одномерным массивом) был приведен к форме, совместимой для поэлементного деления с исходной матрицей.

In [ ]:
A = np.random.randint(1, 10, size=(3, 3))

result = A / A.sum(axis=1)
result_correct = A / A.sum(axis=1).reshape(-1, 1)

A, result, result_correct

(array([[6, 3, 2],
        [3, 5, 9],
        [2, 5, 6]]),
 array([[0.54545455, 0.17647059, 0.15384615],
        [0.27272727, 0.29411765, 0.69230769],
        [0.18181818, 0.29411765, 0.46153846]]),
 array([[0.54545455, 0.27272727, 0.18181818],
        [0.17647059, 0.29411765, 0.52941176],
        [0.15384615, 0.38461538, 0.46153846]]))

## 7. Рассмотрим тензор размерности `(2, 3, 4)`. Какие размерности можно получить при суммирования элементов тензора по осям 0, 1 и 2?

In [ ]:
tensor = np.random.rand(2, 3, 4)

sum_axis_0 = tensor.sum(axis=0).shape
sum_axis_1 = tensor.sum(axis=1).shape
sum_axis_2 = tensor.sum(axis=2).shape

tensor, sum_axis_0, sum_axis_1, sum_axis_2

(array([[[0.57300653, 0.29256586, 0.75350821, 0.04774287],
         [0.32823304, 0.64985425, 0.88535978, 0.22075482],
         [0.7622342 , 0.94498958, 0.64898161, 0.58863543]],
 
        [[0.76391985, 0.95159406, 0.57626523, 0.45808992],
         [0.97300897, 0.45162763, 0.15236525, 0.79967073],
         [0.4849506 , 0.9474747 , 0.18102332, 0.48139901]]]),
 (3, 4),
 (2, 4),
 (2, 3))

## 9. Передайте тензор с 3 или более осями в функцию `linalg.norm` и наблюдайте за его выводом. Что эта функция вычисляет для тензоров произвольной формы?

In [ ]:
tensor = np.random.rand(2, 3, 4)

tensor_norm = np.linalg.norm(tensor)

tensor_norm

2.9168676219957796

При передаче тензора с 3 или более осями в функцию np.linalg.norm, как в нашем случае с тензором размерности (2, 3, 4), функция вычисляет его Фробениусову норму (или евклидову норму для матриц), если не указано иное. Эта норма является обобщением евклидовой нормы для матриц и тензоров и вычисляется как квадратный корень из суммы квадратов всех элементов тензора.

## 10. Определите 3 матрицы $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ и $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{14}}$, содержащие случайные переменные, распределенные по нормальному закону распределения. Вычислите произведение матриц: $\mathbf{A} \mathbf{B} \mathbf{C}$. Есть ли какая-либо разница в объеме памяти и скорости в зависимости от того, вычилсяете Вы $(\mathbf{A} \mathbf{B}) \mathbf{C}$ или $\mathbf{A} (\mathbf{B} \mathbf{C})$. Объясните результаты?

In [9]:
import time
%load_ext memory_profiler
A_shape = (2**10, 2**16)
B_shape = (2**16, 2**5)
C_shape = (2**5, 2**14)

A = np.random.normal(loc=0.0, scale=1.0, size=A_shape)
B = np.random.normal(loc=0.0, scale=1.0, size=B_shape)
C = np.random.normal(loc=0.0, scale=1.0, size=C_shape)

In [20]:
# Вычисляем (AB)C
start_time = time.time()
%memit AB_C = A.dot(B).dot(C)
end_time = time.time()
print("Размерность результата (AB)C:", AB_C.shape)
print("Время выполнения (AB)C:", end_time - start_time, "секунд")

peak memory: 1254.99 MiB, increment: 128.02 MiB
Размерность результата (AB)C: (1024, 16384)
Время выполнения (AB)C: 0.7276597023010254 секунд


In [21]:
# Вычисляем A(BC)
start_time = time.time()
%memit A_BC = A.dot(B.dot(C))
end_time = time.time()
print("Размерность результата A(BC):", A_BC.shape)
print("Время выполнения A(BC):", end_time - start_time, "секунд")

peak memory: 9447.07 MiB, increment: 8320.03 MiB
Размерность результата A(BC): (1024, 16384)
Время выполнения A(BC): 78.50570487976074 секунд


In [22]:
start_time = time.time()
%memit product = A.dot(B).dot(C)
end_time = time.time()
print("Размерность результата ABC:", product.shape)
print("Время выполнения ABC:", end_time - start_time, "секунд")

peak memory: 1255.08 MiB, increment: 128.00 MiB
Размерность результата ABC: (1024, 16384)
Время выполнения ABC: 0.6194963455200195 секунд


Разница имеется, так как проводятся операции с разными размерами матриц при использовании скобок, также при прямом умножении могут использоваться оптимизации в пакете Numpy для уменьшения времени выполнения операции.

## 11. Определите 3 матрицы $\mathbf{A} \in \mathbb{R}^{2^{10} \times 2^{16}}$, $\mathbf{B} \in \mathbb{R}^{2^{16} \times 2^{5}}$ and $\mathbf{C} \in \mathbb{R}^{2^{5} \times 2^{16}}$. Есть ли какая-либо разница в объеме памяти и скорости в зависимости от того, вычилсяете Вы $\mathbf{A} \mathbf{B}$ или $\mathbf{A} \mathbf{C}^\top$? Объясните результаты? Что изменится, если обозначить $\mathbf{C} = \mathbf{B}^\top$ без процедуры клонирования памяти?

In [23]:
A_shape = (2**10, 2**16)
B_shape = (2**16, 2**5)
C_shape = (2**5, 2**16)

A = np.zeros(A_shape, dtype=np.float32)
B = np.zeros(B_shape, dtype=np.float32)
C = np.zeros(C_shape, dtype=np.float32)

In [24]:
start_time = time.time()
%memit AB = np.dot(A, B)
AB_time = time.time() - start_time
print(f"Время выполнения A*B: {AB_time} секунд")

peak memory: 596.68 MiB, increment: 0.11 MiB
Время выполнения A*B: 0.413987398147583 секунд


In [25]:
start_time = time.time()
%memit ACt = np.dot(A, C.T)
ACt_time = time.time() - start_time
print(f"Время выполнения A*C^T: {ACt_time} секунд")

peak memory: 596.84 MiB, increment: 0.12 MiB
Время выполнения A*C^T: 0.3605806827545166 секунд


Время выполнения различается из-за различных оптимизаций при работе с памятью транспонированных матриц

In [26]:
A_shape = (2**10, 2**16)
B_shape = (2**16, 2**5)
A = np.zeros(A_shape, dtype=np.float32)
B = np.zeros(B_shape, dtype=np.float32)
C = B.T

In [27]:
start_time_ACt = time.time()
%memit ACt = np.dot(A, C.T)
end_time_ACt = time.time()
print(f"Время выполнения A*C^T (где C = B^T без дополнительного копирования): {end_time_ACt - start_time_ACt} секунд")

peak memory: 597.57 MiB, increment: 0.00 MiB
Время выполнения A*C^T (где C = B^T без дополнительного копирования): 0.3827974796295166 секунд


## 12. Определите 3 матрицы $\mathbf{A}, \mathbf{B}, \mathbf{C} \in \mathbb{R}^{100 \times 200}$. Сформируйте тензор с 3-мя осями путем объединения матриц $[\mathbf{A}, \mathbf{B}, \mathbf{C}]$. Какова размерность софрмирвоанного тензора? Вырежьте вторую координату третьей оси, чтобы восстановить $\mathbf{B}$. Проверьте, что ваш ответ правильный.

In [ ]:
A = np.random.rand(100, 200)
B = np.random.rand(100, 200)
C = np.random.rand(100, 200)

tensor = np.stack([A, B, C], axis=0)  # Объединение вдоль новой оси

tensor_shape = tensor.shape
print("Размер матрицы -", tensor_shape)
B_recovered = tensor[1, :, :]

is_correct = np.array_equal(B_recovered, B)
print("Проверка ответа -", is_correct)

Размер матрицы - (3, 100, 200)
Проверка ответа - True
